image: maven:3.6.3-jdk-11



test:
  stage: test
  script:
    - mvn clean install
  artifacts:
    when: always


staging:
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install faraday -v 1.9.3
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_SPRING_1 --api-key=$HEROKU_API_KEY