image: maven:3.6.3-jdk-11

deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=prac-spring-1 --api-key=$HEROKU_API_KEY

stages:
  - Test

Test:
  stage: Test
  script:
    - mvn clean install
  artifacts:
    when: always