image: maven:3.6.3-jdk-11



Test:
  stage: Test
  script:
    - mvn clean install
  artifacts:
    when: always


staging:
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=HEROKU_APP_SPRING_1 --api-key=$HEROKU_API_KEY