image: maven:3.6.3-jdk-14

test:
  stage: test
  script:
    - mvn clean install
  artifacts:
    when: always


staging:
  stage: deploy
  before_script:
    - yum update -qy
    - yum install rubygems
    - yum install faraday -v 1.9.3
    - yum install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_SPRING_1 --api-key=$HEROKU_API_KEY