app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-34-230-198-12.compute-1.amazonaws.com:5432/d7c9qcp5bkqi59
    username: nfspvrbgvpkacy
    password: 1ca388875d5c562a9a749b9da04d9d0376808b0d925ca599225e02a287495393
    pool-size: 20


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: acadianapowerandservices@gmail.com
    password: tcdrrekskeimrvof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 314988248131-cajd0q3js5ss1bdg4vuce1fgghtnnage.apps.googleusercontent.com
            client-secret: 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

sms:
  sid: AC3c5a0225fe60910a5d852ba894d0782c
  auth:
    token: 76e295b2d0c1dd460d04552eb3d1b656

company:
  phone: +19036238706

weather:
  api:
    key: f107bb99b733e059dbfec38e8fef3e0b

#jasypt:
#  encryptor:
#  algorithm: PBEWITHHMACSHA512ANDAES_256
#    iv:
#    generator:
#    classname:
#      org:
#        jasypt:
#           iv: NoIvGenerator
#    property:
#      prefix: "ENC@["
#      suffix: "]"