app:
  datasource:
    jdbc-url: "${HEROKU_DB_URL}"
    username: "${HEROKU_DB_USER}"
    password: "${HEROKU_DB_KEY}"
    pool-size: 19


spring:
  mail:
    host: "${SPRING_MAIL_HOST}"
    port: "${SPRING_MAIL_PORT}"
    username: "${SPRING_MAIL_USER}"
    password: "${SPRING_MAIL_KEY}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${OAUTH_ID}"
            client-secret: "${OAUTH_KEY}"

sms:
  sid: "${SMS_SID}"
  auth:
    token: "${SMS_TOKEN}"

company:
  phone: "${COMPANY_PHONE}"

weather:
  api:
    key: "${WEATHER_API_KEY}"
